### ISSUE TITLE
Only working numbers, alphabets and underscore

### ISSUE THREAD

**Issue by abstractindia** [bachors/jQuery-Prefix-Input#1]
I am trying to prefix +91- for all telephone inputs. But its not working. When I remove +  and - it works. Any idea why it does not work with + or -?

**Comment by bachors** [comment]
are you sure?
here works well <code>data-prefix="+91-"</code> http://ibacor.com/download/demo/prefix-input/

**Comment by bachors** [comment]
oh I'm sorry. does not work when pressing the backspace?

**Comment by bachors** [comment]
done I to fix it :)

**Comment by abstractindia** [comment]
where is the demo? any jsfiddle or pastebin?

**Comment by bachors** [comment]
demo => http://codepen.io/bachors/pen/yeJOrg

**Comment by abstractindia** [comment]
Thanks, Its fantastic...
