### ISSUE TITLE
Does not work with number prefix

### ISSUE THREAD

**Issue by VerdonTrigance** [bachors/jQuery-Prefix-Input#2]
For example, data-prefix='160225' determines as int insde 
`$(".ibacor_fi").focus(function(){var a=$(this).data("prefix") . . .`
I think this is cause a problem

**Comment by bachors** [comment]
thank's i have to fix it https://github.com/bachors/jQuery-Prefix-Input/commit/a1ef64bc5ef3283e8b00912f4e3da5b58d308a3a
